var user = {
    queryAll: 'select * from users',
    login: 'select * from users where (uname=? or tel=? or email= ?) and upassword=?',
    req_sel: 'select * from users where uname=? or tel=? or email=?',
    req_ins: 'insert into users values (default,?,?,?,?)',
    //index
    index_sel: 'select * from goods where other like ?',
    goods_order_bnum: 'select * from goods order by bnum desc',
    goods_order_lnum: 'select * from goods order by lnum desc',
    //list
    list_sel_: 'select * from goods where (brand like ?) and (kind like ?) and (tag like ?) and (suit like ?) and (price between ? and ?)',
    list_sel_all: 'select * from goods where (brand like ?) or (kind like ?) or (tag like ?)',
    list_sel_price: 'select * from goods where (brand like ?) and (kind like ?) and (tag like ?) and (suit like ?) and (price between ? and ?) order by price',
    list_sel_bnum: 'select * from goods where (brand like ?) and (kind like ?) and (tag like ?) and (suit like ?) and (price between ? and ?) order by bnum',
    list_sel_lnum: 'select * from goods where (brand like ?) and (kind like ?) and (tag like ?) and (suit like ?) and (price between ? and ?) order by lnum',
    list_sel_sdate: 'select * from goods where (brand like ?) and (kind like ?) and (tag like ?) and (suit like ?) and (price between ? and ?) order by sdate',
    details_sel: 'select * from goods where ID=?',
    details_update_l: 'update goods set lnum=lnum+1 where ID=?',
    details_update_d: 'update goods set bnum=bnum+? , num=num-? where ID=?',
    cart_sel: 'select * from cart where uid=?',
    cart_ins: 'insert into cart values(?,?,?,?)',
    cart_del: 'delete from cart where uid=? and gid =?',
    dingdan_add: 'insert into dingdan values (?,?,?,?,?,?,?,?,?)',
    dingdan_sel: 'select * from dingdan where ID=?',
    dingdan_sel_byuser: 'select * from dingdan where duid=? and status=?',
    dingdan_update: 'update dingdan set address=? , time=? , status=? where ID=?',
    dingdan_shouhuo: 'update dingdan set status=? where ID=? and dgid=?',
    goods_update: 'update goods set num=num-? , bnum=bnum+? where ID=?',
    comment_sel: 'select * from goods_comment where gid=?',
    comment_add: 'insert into goods_comment values (?,?,?,?)',
    like_add: 'insert into users_like (luid) values (?)',
    like_update_act: 'update users_like set age=? , price=? , need=? , skin=? where luid=?',
    like_update_l: 'update users_like set lgid=? where luid=?',
    like_update_b: 'update users_like set bgid=? where luid=?',
    like_sel_act: 'select * from users_like where luid=?',
    goods_sel: 'select * from goods where tag like ? and suit like ? and (price>=? and price<=?)',
    article_sel: 'select * from article where tag like ?'
};
module.exports = user;